hiphop_artists = [  # 377 names approx
    "Drake",
    "Kanye West",
    "Eminem",
    "Kendrick Lamar",
    "J. Cole",
    "Travis Scott",
    "Future",
    "21 Savage",
    "Lil Wayne",
    "Nicki Minaj",
    "Cardi B",
    "Tyler, the Creator",
    "Lil Baby",
    "The Notorious B.I.G.",
    "2Pac",
    "Nas",
    "Jay-Z",
    "Dr. Dre",
    "Ice Cube",
    "N.W.A.",
    "50 Cent",
    "A$AP ROCKY",
    "Young Thug",
    "Gunna",
    "Dave",
    "Central Cee",
    "Playboi Carti",
    "Lil Uzi Vert",
    "YoungBoy Never Broke Again",
    "Akon",
    "The WeekndPublic Enemy",
    "LL Cool J",
    "Slick Rick",
    "KRS-One",
    "De La Soul",
    "Geto Boys",
    "Eric B. & Rakim",
    "EPMD",
    "Boogie Down Productions",
    "Snoop Dogg",
    "Mobb Deep",
    "Common",
    "Busta Rhymes",
    "Foxy Brown",
    "Lil' Kim",
    "Outkast",
    "Bone Thugs-N-Harmony",
    "Master P",
    "Juvenile",
    "Scarface",
    "Mos Def",
    "Talib Kweli",
    "DMX",
    "Ja Rule",
    "Missy Elliott",
    "Method Man",
    "Redman",
    "GZA",
    "Raekwon",
    "Ghostface Killah",
    "Jadakiss",
    "Styles P",
    "Cam'ron",
    "The Diplomats",
    "Three 6 Mafia",
    "UGK",
    "Goodie Mob",
    "Fat Joe",
    "Big Pun",
    "Dilated Peoples",
    "Hieroglyphics",
    "Jurassic 5",
    "Gang Starr",
    "Kurupt",
    "Daz Dillinger",
    "Xzibit",
    "M.O.P.",
    "Dead Prez",
    "Black Star",
    "Pete Rock & CL Lmooth",
    "Souls of Mischief",
    "Del the Funky Homosapien",
    "Brand Nubian",
    "Poor Righteous Teachers",
    "Main Source",
    "Black Sheep",
    "Onyx",
    "FU-Schnickens",
    "Lord Finesse",
    "Big L",
    "The Pharcyde",
    "Smif-N-Wessun",
    "Lost Boyz",
    "Organized Konfusion",
    "Company Flow",
    "Gravediggaz",
    "Jungle Brothers",
    "Biz Markie",
    "Kool G Rap",
    "Ultramagnetic MCs",
    "Heavy D & The Boyz",
    "Whodini",
    "MC Lyte",
    "Special Ed",
    "Big Daddy Kane",
    "Eazy-E",
    "Above the Law",
    "Compton's Most Wanted",
    "Too $hort",
    "MC Ren",
    "The D.O.C.",
    "Warren G",
    "Nate Dogg",
    "Tha Dogg Pound",
    "8Ball & MJG",
    "Clipse",
    "Pharoahe Monch",
    "Rakim",
    "Kool Moe Dee",
    "Sugarhill Gang",
    "T.I.",
    "The Game",
    "G-Unit",
    "Lloyd Banks",
    "Tony Yayo",
    "Young Buck",
    "Lil Jon",
    "Ying Yang Twins",
    "Mike Jones",
    "Paul Wall",
    "Chamillionaire",
    "Yung Joc",
    "Soulja Boy",
    "T-Pain",
    "Plies",
    "Rick Ross",
    "Gucci Mane",
    "Jeezy",
    "Kid Cudi",
    "Lupe Fiasco",
    "Wale",
    "B.o.B",
    "N.E.R.D.",
    "Twista",
    "Fabolous",
    "Ashanti",
    "Nivea",
    "Ciara",
    "Keyshia Cole",
    "The-Dream",
    "Ryan Leslie",
    "Ne-Yo",
    "Chris Brown",
    "Usher",
    "Mary J. Blige",
    "R. Kelly",
    "Destiny's Child",
    "Aaliyah",
    "Janet Jackson",
    "Mariah Carey",
    "Trey Songz",
    "Jeremih",
    "Mario",
    "Sammie",
    "Omarion",
    "Lloyd",
    "Keri Hilson",
    "JoJo",
    "B2K",
    "Bow Wow",
    "Gwen Stefani",
    "Shyne",
    "Beanie Sigel",
    "Freeway",
    "Memphis Bleek",
    "Bubba Sparxxx",
    "David Banner",
    "Chingy",
    "J-Kwon",
    "Murphy Lee",
    "Petey Pablo",
    "Trina",
    "Remy Ma",
    "Shawnna",
    "Mase",
    "The LOX",
    "Migos",
    "Offset",
    "Quavo",
    "Takeoff",
    "Pop Smoke",
    "Roddy Ricch",
    "Moneybagg Yo",
    "Polo G",
    "NLE Choppa",
    "Jack Harlow",
    "Megan Thee Stallion",
    "Ice Spice",
    "Lizzo",
    "H.E.R.",
    "Ella Mai",
    "Summer Walker",
    "Skepta",
    "Stormzy",
    "AJ Tracey",
    "Giggs",
    "Denzel Curry",
    "J.I.D.",
    "Joey Bada$$",
    "Flatbush Zombies",
    "The Underachievers",
    "Logic",
    "Big Sean",
    "Tory Lanez",
    "Nav",
    "6ix9ine",
    "Kodak Black",
    "G Herbo",
    "YNW Melly",
    "XXXTentacion",
    "Ski Mask The Slump God",
    "Lil Peep",
    "Lil Skies",
    "Lil Yachty",
    "Rich Homie Quan",
    "Young Dolph",
    "Key Glock",
    "Rod Wave",
    "Blueface",
    "Saweetie",
    "City Girls",
    "Bia",
    "Coi Leray",
    "Latto",
    "Lil Tjay",
    "Lil Tecca",
    "Lil Mosey",
    "Lil Pump",
    "Smokepurpp",
    "Trippie Redd",
    "Juice WRLD",
    "Lil Durk",
    "King Von",
    "Tee Grizzley",
    "42 Dugg",
    "Babyface Ray",
    "EST Gee",
    "Nardo Wick",
    "Sada Baby",
    "Veeze",
    "Baby Keem",
    "Don Toliver",
    "070 Shake",
    "Sheck Wes",
    "The Kid Laroi",
    "Rema",
    "Burna Boy",
    "Wizkid",
    "Davido",
    "Tems",
    "Amaarae",
    "Ayra Starr",
    "Tyla",
    "Luh Tyler",
    "Yeat",
    "Ken Carson",
    "Destroy Lonely",
    "GloRilla",
    "Sexyy Red",
    "Kali",
    "Flo Milli",
    "Baby Tate",
    "Doechii",
    "Cochise",
    "Yung Gravy",
    "bbno$",
    "A Boogie wit da Hoodie",
    "Meek Mill",
    "Pusha T",
    "2 Chainz",
    "Wiz Khalifa",
    "Mac Miller",
    "Action Bronson",
    "ScHoolboy Q",
    "Ab-Soul",
    "Jay Rock",
    "Isaiah Rashad",
    "Vince Staples",
    "Freddie Gibbs",
    "Run the Jewels",
    "El-P",
    "Killer Mike",
    "GoldLink",
    "Aminé",
    "Kyle",
    "Chance the Rapper",
    "Vic Mensa",
    "Noname",
    "Saba",
    "Earl Sweatshirt",
    "MF DOOM",
    "Madlib",
    "MC Hammer",
    "Vanilla Ice",
    "Coolio",
    "Skee-Lo",
    "Shop Boyz",
    "Mims",
    "D4L",
    "Rich Boy",
    "Silkk the Shocker",
    "Crazy Town",
    "House of Pain",
    "Kris Kross",
    "Sir Mix-a-Lot",
    "Tag Team",
    "69 Boyz",
    "Quad City DJ's",
    "Montell Jordan",
    "Mark Morrison",
    "Ini Kamoze",
    "Snow",
    "Rob Base & DJ E-Z Rock",
    "Tone-Loc",
    "Young MC",
    "Paperboy",
    "Positive K",
    "Afroman",
    "Terror Squad",
    "Jibbs",
    "Dem Franchize Boyz",
    "Unk",
    "Hurricane Chris",
    "Cali Swag District",
    "New Boyz",
    "Roscoe Dash",
    "Waka Flocka Flame",
    "Trinidad James",
    "Ca$h Out",
    "Kirko Bangz",
    "Desiigner",
    "O.T. Genasis",
    "ILoveMakonnen",
    "Rich Gang",
    "Sheff G",
    "Sleepy Hallow",
    "22Gz",
    "Lil Mabu",
    "Stunna 4 Vegas",
    "BlocBoy JB",
    "Famous Dex",
    "Ugly God",
    "Comethazine",
    "YBN Nahmir",
    "YBN Cordae",
    "JackBoys",
    "Cactus Jack",
    "Pardison Fontaine",
    "Teejayx6",
    "Yung Manny",
    "Rae Sremmurd",
    "Swae Lee",
    "Slim Jxmmi",
    "MadeinTYO",
    "KYLE",
    "Roy Woods",
    "PARTYNEXTDOOR",
    "DVSN",
    "Majid Jordan",
    "Bryson Tiller",
    "6LACK",
    "Frank Ocean",
    "Daniel Caesar",
    "Giveon",
    "Brent Faiyaz",
    "SiR",
    "Lucky Daye",
    "Anderson .Paak",
    "Kaytranada",
    "Thundercat",
    "Steve Lacy",
    "Smino",
    "Masego",
    "EarthGang",
    "Spillage Village",
]
